# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Caprover Depolyment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
  APP_URL: ${{ secrets.CAPROVER_APP_URL }}
  APP_NAME: ${{ secrets.CAPROVER_APP_NAME }}

jobs:
  build:

    runs-on: ubuntu-latest

   

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
     
    - run: npm config set strict-ssl false
    
    # Install Caprover CLI, which we use to deploy images to Caprover
    - name: 'Install caprover-cli'
      run: npm install -g caprover
    - name: 'Deploy App to Caprover'
      run: 'caprover deploy -h $APP_URL --appToken $APP_TOKEN -b main -a $APP_NAME'
