# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Caprover Depolyment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

   

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
     
    - run: npm ci
    - run: npm run build --if-present
    - run: tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./build/*
    # Install Caprover CLI, which we use to deploy images to Caprover
    - name: 'Install caprover-cli'
      run: npm install -g caprover
    - name: 'Deploy App to Caprover'
      env:
        APP_TOKEN: ${{ secrets.CAPROVER_APP_TOKEN }}
        APP_URL: ${{ secrets.CAPROVER_APP_URL }}
      run: 'caprover deploy -t ./deploy.tar --caproverUrl=$APP_URL'
